CREATE DATABASE AmonetDb;
GO
USE AmonetDb;
GO

CREATE TABLE dbo.Clients
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    FullName NVARCHAR(120) NOT NULL,
    Email NVARCHAR(120) NULL,
    Phone NVARCHAR(40) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
);

CREATE TABLE dbo.Artists
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    StageName NVARCHAR(120) NOT NULL,
    Styles NVARCHAR(200) NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE dbo.Beds
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    Code NVARCHAR(50) NOT NULL UNIQUE,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE dbo.Appointments
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ClientId UNIQUEIDENTIFIER NOT NULL,
    ArtistId UNIQUEIDENTIFIER NOT NULL,
    BedId UNIQUEIDENTIFIER NOT NULL,
    StartsAt DATETIME2 NOT NULL,
    EndsAt DATETIME2 NOT NULL,
    Status NVARCHAR(20) NOT NULL DEFAULT N'Created',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Appointments_Clients FOREIGN KEY (ClientId) REFERENCES dbo.Clients(Id),
    CONSTRAINT FK_Appointments_Artists FOREIGN KEY (ArtistId) REFERENCES dbo.Artists(Id),
    CONSTRAINT FK_Appointments_Beds FOREIGN KEY (BedId) REFERENCES dbo.Beds(Id)
);

CREATE TABLE dbo.AuditLogs
(
    Id BIGINT IDENTITY PRIMARY KEY,
    Action NVARCHAR(100) NOT NULL,
    PerformedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Data NVARCHAR(MAX) NULL
);

INSERT INTO dbo.Artists(StageName, Styles) VALUES (N'Luna', N'Linework, Realismo');
INSERT INTO dbo.Beds(Code) VALUES (N'BED A'), (N'BED B');
